Commands:
  Admin:
    permission: "custom-entites.admin"
    aliases:
      - ce:admin
  Remove:
    permissions: "custom-entites.remove"
    aliases:
      - ce:remove
  Spawn:
    permissions: "custom-entites.remove"
    aliases:
      - ce:spawn
