# For the Json files:
# x,y,z is relativ to the players position, which is rounded to the block center
# Blocks are the blocks that are actually placed
# Entities are displaced through block/itemsisplays

Commands:
  Admin:
    permission: "custom-entites.admin"
    aliases:
      - ce:admin
  Remove:
    permissions: "custom-entites.remove"
    aliases:
      - ce:remove
  Spawn:
    permissions: "custom-entites.remove"
    aliases:
      - ce:spawn
